<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InvProSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        DB::table('invpro')->insert([
                //UNIDAD 1
            [
                'Titulo'=>'CONCEPTO DE SISTEMAS DE INFORMACIÓN
                QUE ES?... COMO SE USAN?...',
                'Descripcion'=>'Un sistema de información (SI) es un conjunto de componentes interrelacionados que trabajan juntos para recopilar, procesar, almacenar y difundir información para apoyar la toma de decisiones. También apoyan la coordinación, control, análisis y visualización de la organización.',
                'Parrafo1'=>'¿COMO SE USAN?',
                'Parrafo2'=>'La mayoría de las empresas modernas dependen en gran medida de los sistemas para administrar sus operaciones y tomar decisiones. Desde el correo electrónico hasta la gestión de bases de datos y sitios web. Aunque los sistemas de información pueden usarse de manera diferente dentro de una organización, todos tienen los siguientes componentes:',
                'Parrafo3'=>'Hardware: los sistemas utilizan hardware local como una computadora o servicios de Nube para su ejecución.',
                'Parrafo4'=>'Software: estos son los programas utilizados para administración, procesamiento y análisis.',
                'Parrafo5'=>'Bases de datos: los sistemas trabajan con recursos organizados en tablas y archivos.',
                'Parrafo6'=>'Red: se deben conectar diferentes recursos entre sí, especialmente si muchas personas diferentes en una organización usan el mismo sistema.',
                'Parrafo7'=>'Procedimientos: describen cómo se procesan y analizan los datos y recursos específicos para obtener las respuestas para las que está diseñado el sistema (“lógica del negocio”).',
                'Parrafo8'=>'Cada sistema de información está compuesto por una serie de recursos interrelacionados que interactúan y se ordenan de la manera más conveniente de acuerdo con el propósito de información planteado, como la recopilación de información personal, el procesamiento de datos estadísticos, la organización de documentos, etc. Estos recursos pueden ser:',
                'Parrafo9'=>'Recursos humanos. Personal de variada índole y destrezas.',
                'Parrafo10'=>'Datos. Cualquier tipo de información masiva que precisa de organizarse.',
                'Parrafo11'=>'Actividades. Procedimientos, pasos a seguir, estaciones de trabajo, etc.',
                'Parrafo12'=>'TIPOS DE SISTEMAS DE INFORMACIÓN',
                'Parrafo13'=>'Sistemas de Procesamiento de Transacciones (TPS). También conocidos como sistemas de gestión operativa, recopilan la información pertinente a las transacciones de la organización, es decir, de su funcionamiento.',
                'Parrafo14'=>'Sistemas de Información Ejecutiva (EIS). Monitoriza las variables gerenciales de un área específica de la organización, a partir de la información interna y externa de la misma.',
                'Parrafo15'=>'Sistemas de Información Gerencial (MIS). Contemplan la información general de la organización y la comprenden como un todo.',
                'Parrafo16'=>'Sistemas de soporte de decisiones (DSS). Orientados al procesamiento de información intra y extra organizacional, para el apoyo en la conducción de la empresa.',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'1',
                'Imagen'=>'https://hurtful-sprayers.000webhostapp.com/images/muest-sis-info.jpg',
                'slug'=>'concepto_sistemas_de_informacion',
            ],
            [
                'Titulo'=>'EVOLUCIÓN...',
                'Descripcion'=>'1950 - 1960: PROCESAMIENTO DE DATOS ELECTRÓNICOS, SISTEMA DE PROCESAMIENTO DE TRANSACCIONES',
                'Parrafo1'=>'A lo largo de este lapso, el papel del sistema de información era primordialmente hacer ocupaciones como el procesamiento de transacciones, el mantenimiento de registros y la contabilidad. SI se usa primordialmente para el procesamiento electrónico de datos. Además conocido como procesamiento de información o procesamiento automático de datos. Un Sistema de procesamiento de transacciones (TPS) ha sido el primer sistema computarizado desarrollado para procesar datos comerciales. TPS principalmente informatiza o automatiza los procesos manuales existentes para un procesamiento más veloz, un mejor servicio al comprador y precios administrativos más bajos. TPS además se sabe como procesamiento de transacciones o procesamiento en tiempo real.',
                'Parrafo2'=>'1960 A 1970: SISTEMAS DE INFORMACIÓN GERENCIAL',
                'Parrafo3'=>'Durante esta era, el rol de SI evolucionó desde TPS hasta Management Information Systems (MSI) o Sistemas de información gerenciales. MSI procesa los datos en informes informativos útiles y proporciona a los gerentes las herramientas para organizar evaluar y administrar de manera eficiente los departamentos dentro de una organización.',
                'Parrafo4'=>'1970 A 1980: SISTEMAS DE SOPORTE DE DECISIONES',
                'Parrafo5'=>'El papel se centró en el "sistema interactivo con base en pcs" para contribuir a los causantes de la toma de elecciones a solucionar inconvenientes. Este nuevo papel de los sistemas de información para dar soporte ad-hoc interactivo para el proceso de toma de elecciones a los gerentes y otros expertos de negocios se llama Sistemas de Soporte de Decisiones (DSS). DSS sirve el nivel de planificación, gestión y operaciones de una organización, por lo general, la alta dirección. DSS usa datos de fuentes internas y/o externas. Las fuentes internas de datos tienen la posibilidad de integrar datos de inventario, ventas, construcción o financieros de la base de datos de una organización. Las fuentes externas podrían integrar costos, tasas de interés, población o tendencias. Los gerentes utilizan DSS para manipular los datos y favorecer con las decisiones.',
                'Parrafo6'=>'1980 A 1990: SISTEMAS DE INFORMACIÓN EJECUTIVO',
                'Parrafo7'=>'Este período dio lugar a la informática departamental debido a que muchas organizaciones compran su propio hardware y software para satisfacer sus necesidades departamentales. En vez de aguardar el apoyo indirecto del departamento de servicio corporativo centralizado, los empleados podrían utilizar sus propios recursos para respaldar sus requisitos laborales. Además, los elevados ejecutivos no utilizaban DSS ni MSI, por lo cual se desarrollaron sistemas de información ejecutivo (ESI) o sistemas de soporte ejecutivo (ESS).

                ESI da servicios de toma de elecciones a los ejecutivos por medio del abastecimiento de información interna y externa importante para consumar las metas estratégicos de la organización. Los ejemplos del ESI son sistemas para facilitar la entrada a las ocupaciones de todos los participantes, desarrollos económicos para respaldar la organización estratégica y la exploración del funcionamiento del comercio.',
                'Parrafo8'=>'1990 A 2000: SISTEMAS DE GESTIÓN DEL CONOCIMIENTO',
                'Parrafo9'=>'Durante esta era, el rápido crecimiento de las intranets, extranets, internet y otras redes globales interconectadas cambiaron drásticamente las capacidades de SI en los negocios. Se hizo posible circular el conocimiento a diferentes partes del mundo independientemente del tiempo y el espacio. Este lapso además vio una aparición de sistemas de planeación de recursos empresariales (ERP). ERP es una manera específica de organización de un sistema de información estratégica que añade todos los elementos de una organización, incluidas la construcción, las ventas, la administración de recursos, la planeación de recursos humanos y el marketing.

                Sistemas expertos (ES) y sistemas de gestion de conocimiento (KMS) interconectados entre sí. Los sistemas expertos (ES) son un sistema informático que copia la función de toma de decisiones de los expertos humanos. El sistema de gestion de conocimiento (KMS) es un sistema de TI que almacena y recupera entendimiento para auxiliar la construcción, organización y diseminación del entendimiento empresarial en la organización. ES usa datos de los Sistemas de Gestion de Conocimientos para crear un resultado deseable del sistema de información, ejemplificando, un sistema de aprobación de solicitudes de préstamo.',
                'Parrafo10'=>'2000 - PRESENTE: E-BUSINESS',
                'Parrafo11'=>'Internet y las tecnologías y aplicaciones en relación cambiaron la manera en que operan las organizaciones y los individuos trabajan. Las funcionalidades de los sistemas de información en este lapso siguen siendo las mismas que hace 50 años: mantenimiento de registros, administración de informes, procesamiento de transacciones, administración de soporte y procesos de administración de la organización. Muchas organizaciones utilizan tecnologías de Internet y procesos de comercio habilitados para la web para producir aplicaciones innovadoras de negocio electrónico.',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'1',
                'Imagen'=>'',
                'slug'=>'evolucion_de_los_sistemas_de_informacion',
            ],
            [
                'Titulo'=>'CONCEPTO DE CLIENTE SERVIDOR
                QUE ES?... QUE LO COMPONE?...',
                'Descripcion'=>'Este modelo es uno de los más importantes utilizados en muchísimos servicios y protocolos de Internet, por lo cual para todos esos que desean aprender más sobre la web y cómo funciona, comprender el término de modelo cliente servidor se vuelve algo imprescindible. Se denomina cliente al dispositivo que necesita ciertos servicios a un servidor.

                Se llama cliente al dispositivo que requiere ciertos servicios a un servidor. La idea de servidor, por su parte, alude al equipo que brinda servicios a las computadoras que se hallan conectadas con él mediante una red.
                
                El concepto de cliente servidor, o cliente-servidor, refiere por lo tanto a un modelo de comunicación que vincula a varios dispositivos informáticos a través de una red. El cliente, en este marco, realiza peticiones de servicios al servidor, que se encarga de satisfacer dichos requerimientos.Dicho de otro modo: el cliente le pide un recurso al servidor, que brinda una respuesta.',
                'Parrafo1'=>'COMPONENTES',
                'Parrafo2'=>'Red: Una red es un conjunto de clientes, servidores y base de datos unidos de una manera física o no física en el que existen protocolos de transmisión de información establecidos.',
                'Parrafo3'=>'Cliente: El concepto de cliente hace referencia a un demandante de servicios, este cliente puede ser un ordenador como también una aplicación de informática, la cual requiere información proveniente de la red para funcionar.',
                'Parrafo4'=>'Servidor: Un servidor hace referencia a un proveedor de servicios, este servidor a su vez puede ser un ordenador o una aplicación informática la cual envía información a los demás agentes de la red.',
                'Parrafo5'=>'Protocolo: Un protocolo es un conjunto de normas o reglas y pasos establecidos de manera clara y concreta sobre el flujo de información en una red estructurada.',
                'Parrafo6'=>'Servicios: Un servicio es un conjunto de información que busca responder las necesidades de un cliente, donde esta información pueden ser mail, música, mensajes simples entre software, videos, etc.',
                'Parrafo7'=>'Base de datos:Son bancos de información ordenada, categorizada y clasificada que forman parte de la red, que son sitios de almacenaje para la utilización de los servidores y también directamente de los clientes.',
                'Parrafo8'=>'DIFERENCIAS ENTRE CLIENTE Y SERVIDOR',
                'Parrafo9'=>'El cliente es un computador pequeño con una composición al igual a la que poseemos en nuestras propias oficinas u domicilios la cual accede a un servidor o a los servicios del mismo por medio de Internet o una red interna.',
                'Parrafo10'=>'Un claro ejemplo a este caso es la forma en que trabaja una empresa modelo con diferentes computadores donde cada uno de ellos se conectan a un servidor para poder obtener archivos de una base de datos o servicios ya sea correos electrónicos o aplicaciones.',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'1',
                'Imagen'=>'https://hurtful-sprayers.000webhostapp.com/images/eje-cli-ser.jpg',
                'slug'=>'concepto_cliente_servidor',
            ],
            [
                'Titulo'=>'TIPOS DE ARQUITECTURA CLIENTE SERVIDOR
                QUE ES?... TIPOS?...',
                'Descripcion'=>'',
                'Parrafo1'=>'ARQUITECTURA DE DOS CAPAS',
                'Parrafo2'=>'Esta se utiliza para describir los sistemas cliente servidor en donde el cliente solicita recursos y el servidor responde directamente a la solicitud con sus propios recursos. Eso significa que el servidor no requiere de una aplicación extra para proporcionar parte de3 servicio.',
                'Parrafo3'=>'ARQUITECTURA DE TRES CAPAS',
                'Parrafo4'=>'En la arquitectura de tres capas existe un nivel intermediario, eso significa que la arquitectura generalmente está compartida por un cliente que como hablamos más arriba es el que solicita los recursos equipados con una interfaz de usuario o mediante un Parrafo4 web.5
                La capa del medio es denominada software intermedio cuya tarea es proporcionar los recursos solicitados pero que requiere de otro servidor para hacerlo. La última capa es el servidor de datos que proporciona al servidor de aplicaciones los datos necesarios para poder procesar y generar el servicio que solicito el cliente en un principio.',
                'Parrafo5'=>'ARQUITECTURA N CAPAS',
                'Parrafo6'=>'En la arquitectura de tres capas, los servidores dos y tres realizaron una tarea específica por lo tanto un servidor web puede usar los servicios de otros servidores para poder proporcionar su propio servicio.

                Por consiguiente, la arquitectura en tres niveles es potencialmente una arquitectura en N capas ya que así como está contemplado en tres niveles como el caso anterior puede estar compuesto por N servidores donde cada uno de ellos brindan su servicio específico.',
                'Parrafo7'=>'VENTAJAS',
                'Parrafo8'=>'Facilita la integración entre diferentes sistemas y comparte información permitiendo por ejemplo que las máquinas ya existentes puedan ser utilizadas mediante una interfaz más amigable para el usuario. De esta manera podemos integrar varias PCs con sistemas medianos y grandes sin necesidad de que todos tengan que utilizar el mismo sistema operativo. Al favorecer el uso del interfaz de gráficas interactivas, los sistemas construidos bajo este esquema tienen una mayor interacción con el usuario.

                La estructura modular facilita de más la integración de nuevas tecnologías y el crecimiento de la infraestructura computacional favoreciendo así la estabilidad de las soluciones.',
                'Parrafo9'=>'DESVENTAJAS',
                'Parrafo10'=>'Requiere habilidad para que un servidor sea reparado. Por ejemplo, si un problema ocurre en la red, se requiere de alguien con un amplio de esta para poder repararla en su totalidad para así dejar que la información y el correcto funcionamiento siga su flujo.

                Otro problema es la seguridad, el hecho que se comparte canales de información entre servidores y clientes requieren que estas pasen por procesos de validación, es decir protocolos de seguridad que pueden tener algún tipo de puerta abierta permitiendo que se generen daños físicos, amenazas o ataques de malware.
                
                Este modelo representa una limitación importante en cuanto a los costos económicos debido a que estos servidores son computadoras de alto nivel con un hardware y software específicos para poder dar un correcto funcionamiento a nuestras aplicaciones. Algo importante a destacar es que no solo es caro a la hora de solucionar problemas como mencionamos antes, sino que también tiene un costo elevado para reemplazar componentes que estén averiados.',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'1',
                'Imagen'=>'https://hurtful-sprayers.000webhostapp.com/images/ti-ar-clie-ser.jpg',
                'slug'=>'tipos_de_arquitectura',
            ],
            [
                'Titulo'=>'SISTEMAS DE COMPUTADORAS CENTRALES Y DEDICADAS
                QUE ES?... CONCEPTO?...',
                'Descripcion'=>'',
                'Parrafo1'=>'¿QUÉ ES UNA COMPUTADORA CENTRAL?',
                'Parrafo2'=>'Una computadora central (en inglés mainframe) es una computadora grande, potente y costosa usada principalmente por una gran compañía para el procesamiento de una gran cantidad de datos; por ejemplo, para el procesamiento de transacciones bancarias.',
                'Parrafo3'=>'La función de una PC central se define tanto por la rapidez de su CPU como por su enorme memoria interna, su alta y enorme capacidad de almacenamiento externo, sus resultados en los dispositivos E/S rápidos y considerables, la alta calidad de su ingeniería interna que tiene como resultado una alta confiabilidad y soporte técnico caro sin embargo de alta calidad.',
                'Parrafo4'=>'APLICACIÓN',
                'Parrafo5'=>'A diferencia de las Supercomputadoras, ofrecen un entorno de trabajo versátil y simplificado, grandes velocidades de procesamiento a un muy bajo costo con respecto a las antes mencionadas. Tienen muchas más aplicaciones que las Supercomputadoras ya que son más asequibles al mercado corporativo, siendo la solución para grandes supermercados y empresas. Algunas de las aplicaciones son:

                Administración y soporte para grandes redes, así como servidor de aplicaciones web y bases de datos dinámicas y de acceso remoto.
                    
                Investigaciones científicas de nivel bajo y medio, y en algunos casos aislados de nivel superior, como por ejemplo en el desarrollo de simulaciones interactivas sobre el comportamiento de una sustancia X ante la presencia de una Sustancia Y, desarrollando nuevos fármacos y sustancias químicas.',
                'Parrafo6'=>'¿QUÉ ES UNA COMPUTADORA DEDICADA?',
                'Parrafo7'=>'Bueno, de forma resumida, se trata de una computadora con sistema de computación centralizado o software que ofrece servicios a una red de computadoras, conocida como cliente.

                Se trata de un modelo que puede ser tanto para sistemas (como Business Intelligence o ERP como para sitios en que la empresa asegura un servidor totalmente exclusivo en el data center.',
                'Parrafo8'=>'¿CÓMO FUNCIONA UN SERVIDOR DEDICADO?',
                'Parrafo9'=>'En la práctica, un servidor dedicado funciona como si fuera el data center de la propia empresa, pues, posibilita configurar el servicio de la forma que deseas, de acuerdo con las necesidades específicas.

                Como el propio nombre deja claro, este tipo de servidor es dedicado a la organización contratante, lo que significa que el espacio no es dividido con otras empresas, garantizando así, un desempeño mucho mejor.',
                'Parrafo10'=>'SERVIDOR DEDICADO X NO DEDICADO -> DIFERENCIAS',
                'Parrafo11'=>'¿Cuáles son las diferencias entre el servidor dedicado y el no dedicado?

                El servidor dedicado tiene muchos más recursos de almacenamiento y de procesamiento de datos. Como su propio nombre dice, disponibiliza el servicio con total exclusividad para el cliente.
                
                De esta manera, garantiza mejor desempeño y performance para las aplicaciones y sitios web, generando más estabilidad, velocidad, seguridad, entre otros. Es una excelente alternativa para los sitios web que tienen varios accesos y aplicaciones que consumen muchos recursos.',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'1',
                'Imagen'=>'https://hurtful-sprayers.000webhostapp.com/images/com-centrales.jpg',
                'slug'=>'sistemas_de_computadoras_centrales_dedicadas',
                
            ],
            
            [

                'Titulo'=>'Conexión libre y a través de redes',
                'Descripcion'=>'Se abarcara información acerca de la conexión libre y como es su función a través de las redes.',
                'Parrafo1'=>'Internet libre',
                'Parrafo2'=>'Este se puede catalogar como libre, cuando estamos frente a un sistema descentralizado y autosustentable. La descentralización puede tomarse como ejemplo lo que ocurre en las trasmisiones streaming donde es una emisión directa sin intermediarios.',
                'Parrafo3'=>'Internet abierto',
                'Parrafo4'=>'Es un sistema abierto cuando existe transparencia en cada una de las comunicaciones, permitiendo una colaboración grupal de diferentes puntos, compartiendo cualidades e ideas.',
                'Parrafo5'=>'¿Cuál es el objetivo de tener una internet libre y abierta y qué ventajas tiene?',
	            'Parrafo6'=>'Dejando a un lado las desventajas, podremos decir que un Internet libre y abierto nos permite conectarnos y apoyar todos los sectores, incluyendo entre ellos el área de salud humana.',
                'Parrafo7'=>'',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'1',
                'Imagen'=>'https://hurtful-sprayers.000webhostapp.com/images/conexion-lib.jpg',
                'slug'=>'conexion_libre',
            ],  

            [
                'Titulo'=>'DESCRIBIR LOS SISTEMAS CON ARQUITECTURA CLIENTE/SERVIDOR',
                'Descripcion'=>'Se dara a concer las arquitecturas mas comunes',
                'Parrafo1'=>'ARQUITECTURA CLIENTE/SERVIDOR',
                'Parrafo2'=>'Esta arquitectura consiste básicamente en un cliente que realiza peticiones a otro programa (el servidor) que le da respuesta. Aunque esta idea se puede aplicar a programas que se ejecutan sobre una sola computadora es más ventajosa en un sistema operativo multiusuario distribuido a través de una red de computadoras.	',
                'Parrafo3'=>'ARQUITECTURA BASADA EN CAPAS',
                'Parrafo4'=>'La arquitectura en capas consta en dividir la aplicación en capas, con la intención de que cada capa tenga un rol muy definido, como podría ser, una capa de presentación (UI), una capa de reglas de negocio (servicios) y una capa de acceso a datos (DAO),',
                'Parrafo5'=>'ARQUITECTURA EN 3 CAPAS',
                'Parrafo6'=>'Es una arquitectura de software de aplicación bien establecida que separa las aplicaciones en tres niveles de informática lógica y física: el nivel de presentación o la interfaz de usuario, el nivel de aplicación o donde se procesan los datos, y el nivel de datos donde se almacenan y gestionan los datos asociados con la aplicación.',
                'Parrafo7'=>'ARQUITECTURA ORIENTADA A SERVICIOS',
                'Parrafo8'=>'La arquitectura orientada a los servicios (SOA) es un tipo de diseño de software que permite reutilizar sus elementos gracias a las interfaces de servicios que se comunican a través de una red con un lenguaje común. Un servicio es una unidad autónoma de una o más funciones del software diseñada para realizar una tarea específica, como recuperar cierta información o ejecutar una operación. ',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'1',
                'Imagen'=>'https://hurtful-sprayers.000webhostapp.com/images/arquitectura-cliente-servidor.jpg',
                'slug'=>'sistemas_arquitecturas',
            ],
            [
                'Titulo'=>'Programa Maestro',
                'Descripcion'=>'Entonces, el Proyecto Maestro de Producción es una calendarización que refleja la capacidad real de cada proceso de la cadena de producción, así como la demanda de productos. 
                Además, las metas del PMP van muchísimo más allá que la fácil optimización de nuestros propios niveles de cumplimiento de la demanda: además tenemos la posibilidad de lograr que en cada proceso de producción aprovechemos de forma óptima los materiales y recursos con los que contamos.',
                'Parrafo1'=>'El personal y recursos involucrados en la producción.',
                'Parrafo2'=>'El volumen por producir, con sus fechas límite.',
                'Parrafo3'=>'Nivel de inventarios o cantidad de productos actualmente disponibles.',
                'Parrafo4'=>'La capacidad que estará libre para futuros pedidos.',
                'Parrafo5'=>'El proceso de un MPS siempre comienza por conocer los niveles de inventario, nuestra capacidad de producción y los requerimientos de entrega de los clientes, o bien, la demanda que esperamos tener. Si contamos con un sistema ERP (Planificador de Recursos Empresariales), o bien, un MRP (Planificador de Requerimiento de Materiales), tenemos la posibilidad de obtener esta información con unos cuantos clics. ',
                'Parrafo6'=>'',
                'Parrafo7'=>'',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'1',
                'Imagen'=>'https://www.aner.com/media/k2/items/cache/6c16f95e5837b7a15cc22a32eb72fad8_L.jpg',
                'slug'=>'programa_maestro',
            ],
            [
                'Titulo'=>'Tipos de servidores',
                'Descripcion'=>'Es un dispositivo o infraestructura informática que hace parte de una red y provee información a otros servidores. ',
                'Parrafo1'=>'Servidor de email',
                'Parrafo2'=>'Funciona como una especie de oficina de correspondencia para guardar, recibir, mandar y permitir diversas operaciones que deben ver con el correspondencia personal de los consumidores. ',
                'Parrafo3'=>'POP3: retienen los emails recibidos hasta que el cliente los abre, instante en que son enviados al dispositivo (computadora, teléfono, tablet). ',
                'Parrafo4'=>' IMAP: posibilita interactuar con la información recibida como un mensaje de email, sin embargo sin descargarla en los accesorios. ',
                'Parrafo5'=>' Los servidores de email son de los más frecuentes en el mercado, debido a la fama que tiene el correspondencia electrónico en nuestra vida, gracias a su efectividad en términos informativos y de administración.',
                'Parrafo6'=>'Servidor web',
                'Parrafo7'=>'Un servidor web se encarga de guardar la información en formato HTML de los sitios, donde se incluye escrito, imágenes, clip de videos y toda clase de datos. Mediante un explorador web, los usuarios puedan visualizar todo esto en sus pantallas. ',
                'Parrafo8'=>'Servidores cloud',
                'Parrafo9'=>'Estos sirven para compañías que se dedican a rentar un espacio en sus servidores para que otras personas o empresas guarden la información de manera remota. Sirven para guardar enormes porciones de datos y de esta forma defender la información de las empresas o personas naturales.',
                'Parrafo10'=>'Servidor DNS',
                'Parrafo11'=>'Su trabajo es generar un parentesco entre el dominio del lugar con su IP (un grupo de números que identifica jerárquica y lógicamente una interfaz en red a un dispositivo). 
                Tal cual, una vez que se redacta un dominio en un explorador, el servidor lee este requerimiento y regresa la información de la interfaz de la página. ',
                'Parrafo12'=>'Servidor Telnet',
                'Parrafo13'=>'Usado primordialmente en las telecomunicaciones, es un protocolo de red que le posibilita a los usuarios gestionar, mandar y recibir datos para resolver inconvenientes con las redes en relación con la telefonía. Asimismo, almacena los datos de los mensajes de voz, contestadoras, encima las llamadas y controla la red del Internet móvil. ',
                'Parrafo14'=>'Servidor SIP',
                'Parrafo15'=>'Es conocido como Proxy SIP y su trabajo es establecer la conexión para llamadas telefónicas por Internet. El mismo no transmite audio ni clip de video; solamente almacenan la dirección IP para crear la comunicación con otro cliente. ',
                'Parrafo16'=>'Servidor FTP',
                'Parrafo17'=>'Es un servidor que está conectado a Internet que posibilita la probabilidad de transferir archivos y datos entre otros pcs y servidores. ',
                'Parrafo18'=>'Servidor del acceso remoto (RAS)',
                'Parrafo19'=>'Vigila las líneas de módem de los ordenadores u otros medios de comunicación de Internet, de manera tal que los requerimientos conecten con la red en forma remota, contesta llamadas e interviene la petición de la red.',
                'Parrafo20'=>'Servidor compartido',
                'Parrafo21'=>'Dan espacio para guardar información y simultáneamente comparte recursos con la memoria RAM, el CPU, el sistema operativo, la conectividad a Internet y la dirección IP.

                Este servidor se utiliza para recibir requerimientos de varios consumidores. La exclusiva desventaja es que los usuarios del servidor compartido no tienen la posibilidad de hacer muchas demandas simultáneamente, debido a que no es suficientemente veloz. ',
                'Unidad'=>'1',
                'Imagen'=>'http://vidabytes.com/wp-content/uploads/2020/06/Modelo-cliente-servidor-4.jpg',
                'slug'=>'tipos_de_servidores',
            ],
            [
                'Titulo'=>'Ventajas e inconvenientes de la arquirectura cliente/servidor',
                'Descripcion'=>'El modelo cliente/servidor está en especial indicado en redes medias o enormes que necesiten un elevado grado de confiabilidad.',
                'Parrafo1'=>'Las principales ventajas que ofrece son:',
                'Parrafo2'=>'Gestión centrada en el servidor. Los consumidores poseen escasa trascendencia en el esquema y sus necesidades de gestión son menores.
                Centralización de los recursos. Los recursos usuales a todos los usuarios se administran en el servidor. De esta forma se evitan situaciones como la redundancia o inconsistencia de información en las bases de datos.
                Optimización de la estabilidad. Al contar con un mecanismo central de autenticación, las maneras de ingreso indebido se disminuyen de manera considerable.
                Escalabilidad de la instalación. Tienen la posibilidad de adicionar o eliminar consumidores sin que el manejo de la red se vea perjudicado. ',
                'Parrafo3'=>'Coste alto. Tanto la instalación como el mantenimiento son más altos debido al perfil bastante técnico del lado servidor.
                Dependencia del servidor. Toda la red está construida al rededor del servidor y si éste deja de funcionar o lo hace con un rendimiento inadecuado, perjudicará a toda la infraestructura.
                Afortunadamente, este último problema está superado, por lo menos en cierta medida, debido a sistemas como los servidores redundantes, la tolerancia a fallos y los sistemas de almacenamiento en modo RAID. ',
                'Parrafo4'=>'',
                'Parrafo5'=>'',
                'Parrafo6'=>'',
                'Parrafo7'=>'',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'1',
                'Imagen'=>'https://media.istockphoto.com/vectors/internet-client-server-architecture-vector-id165731607?k=20&m=165731607&s=612x612&w=0&h=AjnCwWNZd8X31Miksf9J0M-qLeyQZqgQvd5RWWmvKxE=',
                'slug'=>'ventajas_desventajas_arquitectura_cliente_servidor',
            ],
            [
                'Titulo'=>'¿Qué es computación en la nube?',
                'Descripcion'=>'La computación en la nube (o cloud computing, en inglés) es una tecnología que posibilita entrar remotamente, de cualquier sitio de todo el mundo y en cualquier instante, a softwares, almacenamiento de archivos y procesamiento de datos por medio de Internet, sin la necesidad de conectarse a un ordenador personal o servidor local. ',
                'Parrafo1'=>'¿Qué es computación en la nube?',
                'Parrafo2'=>'Si todavía no quedó claro, déjame ejemplificarlo: si alguna vez editaste un documento en Google Docs, escuchaste música en Spotify o viste una película en Netflix, tuviste contacto directo con la computación en la nube. Todos ellos son servicios online que no demandan la descarga, instalación y acceso de ningún tipo de software o archivo en tu ordenador.',
                'Parrafo3'=>'Si analizamos el modelo informático tradicional, donde los usuarios y las empresas deben invertir en descargas, hardware, sistemas operativos y software para poder ejecutar un determinado tipo de aplicación, será fácil ver por qué la computación en la nube es tan predominante.
                La nube ha surgido como una forma de democratizar la información y mejorar la experiencia de quienes dependen de los recursos tecnológicos a nivel personal o profesional.',
                'Parrafo4'=>'Nube publica',
                'Parrafo5'=>'Si analizamos el modelo informático tradicional, donde los usuarios y las empresas deben invertir en descargas, hardware, sistemas operativos y software para poder ejecutar un determinado tipo de aplicación, será fácil ver por qué la computación en la nube es tan predominante.
                La nube ha surgido como una forma de democratizar la información y mejorar la experiencia de quienes dependen de los recursos tecnológicos a nivel personal o profesional.',
                'Parrafo6'=>'Nube privada',
                'Parrafo7'=>'En este modelo, la empresa mantiene la infraestructura de la nube en sus instalaciones y brinda acceso limitado a usuarios específicos, como empleados y socios.
                Una nube privada brinda a las empresas la capacidad de personalizar la funcionalidad y el soporte para satisfacer sus necesidades. Dado que la nube está diseñada específicamente para ello, todas las operaciones están orientadas a las realidades del negocio.',
                'Parrafo8'=>'Nube hibrida',
                'Parrafo9'=>'Finalmente, cuando hablamos de nube híbrida, nos referimos a una combinación de las dos anteriores, o una combinación que les permite compartir datos y aplicaciones entre ellos. Por lo tanto, dependiendo de las necesidades y la estrategia del negocio, algunos recursos se utilizan de forma privada, mientras que otros se utilizan públicamente o se vinculan a través de tecnologías.',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'1',
                'Imagen'=>'http://www.tecnosop.com/wp-content/uploads/2016/10/pcvirtual-300x225.jpg',
                'slug'=>'computo_en_la_nube',
            ],
            [
                'Titulo'=>'Infrastructure as a Service',
                'Descripcion'=>'',
                'Parrafo1'=>'SaaS ',
                'Parrafo2'=>'SaaS le permite acceder al software sin comprar una licencia, de uso gratuito desde la nube, a menudo con recursos limitados',
                'Parrafo3'=>'En este formato, la empresa accede al software en línea sin tener que preocuparse por la instalación, configuración e inversión en licencias.
                Muchos CRM y ERP funcionan a través de SaaS. Los servicios de correo electrónico y otras aplicaciones públicas, como Skype, Whatsapp, LinkedIn y Facebook, también funcionan con este tipo de formulario, por lo que es el mecanismo más popular.',
                'Parrafo4'=>'PaaS ',
                'Parrafo5'=>'En este modelo de nube se contrata un completo entorno de desarrollo bajo demanda en el que se pueden crear, modificar y mejorar software y aplicaciones.
                La ventaja del modelo PaaS es que incluye el sistema operativo, las herramientas de desarrollo, los sistemas de gestión de bases de datos, los servicios de inteligencia empresarial y muchos otros recursos, así como toda la infraestructura necesaria para ejecutar o mejorar las aplicaciones web o móviles.',
                'Parrafo6'=>'IaaS ',
                'Parrafo7'=>'En el modelo IaaS, se alquilan recursos de infraestructura, como servidores, enrutadores, racks, centros de datos, hardware y otras herramientas que permiten la transmisión y el almacenamiento de datos.
                Por ejemplo, según el proveedor y el modelo elegido, se puede cobrar a la empresa por la cantidad de servidores utilizados y la cantidad de datos almacenados o comercializados. En el modelo IaaS, usas lo que la empresa necesita y solo pagas por lo que usas.',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'1',
                'Imagen'=>'https://www.csuc.cat/sites/default/files/2021-02/IaaS.png',
                'slug'=>'infrastructure_as_a_service',
            ],

            //UNIDAD 2

            [
                'Titulo'=>'Arquitectura cliente/servidor',
                'Descripcion'=>'',
                'Parrafo1'=>'Presentación remota',
                'Parrafo2'=>'La capa de presentación de datos se ejecuta completamente en el cliente. Allí, validación de datos de entrada, formato de datos de salida, etc. hecho. La lógica empresarial y el acceso a la base de datos se alojan en el servidor.',
                'Parrafo3'=>'Presentación distribuida',
                'Parrafo4'=>'La capa de presentación se distribuye entre el cliente y el servidor, de manera que la presentación que da el servidor se modifica o adapta al cliente. Este tipo de sistemas son difíciles de mantener.',
                'Parrafo5'=>'Presentación distribuido',
                'Parrafo6'=>'En este modelo, la capa que implementa la lógica empresarial se separa entre el cliente y el servidor. Acceso a la base de datos en el servidor ya la capa de presentación en el cliente.',
                'Parrafo7'=>'Base de datos distribuida',
                'Parrafo8'=>'Las capas de trabajo y presentación se ejecutan completamente en el cliente, mientras que la base de datos se distribuye entre el cliente y el servidor. Se necesita un mecanismo para garantizar la coherencia de los datos.',
                'Parrafo9'=>'Base de datos remota',
                'Parrafo10'=>'Las capas comercial y de presentación se ejecutan completamente en el cliente, mientras que la base de datos se ejecuta completamente en el servidor.',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'2',
                'Imagen'=>'http://isa.uniovi.es/domotica/Temas/T6/T6-ClienteServidor_archivos/image010.jpg',
                'slug'=>'arquitectura_cliente_servidor',
            ],
            [
                'Titulo'=>'Logica de acceso',
                'Descripcion'=>'',
                'Parrafo1'=>'Que es?...',
                'Parrafo2'=>'El control de acceso adecuado es la principal línea de defensa para la mayoría de los sistemas y evita que personas no autorizadas accedan a su información. Se utilizan dos procesos para controlar el acceso: identificación y autenticación.
                Se denomina identidad al momento en que el usuario se identifica en el sistema; y autenticación para verificar que el sistema opera con esta identidad.',
                'Parrafo3'=>'Es más efectivo cuando los usuarios son reconocidos y autenticados una sola vez, y desde allí pueden acceder a todas las aplicaciones y datos que permite su perfil, tanto de forma local como remota. Esto se denomina inicio de sesión único o sincronización de contraseñas.',
                'Parrafo4'=>'Logica negocio de datos',
                'Parrafo5'=>'El término lógica de negocios se refiere a la parte del sistema responsable de codificar las reglas comerciales reales que definen cómo se crea, almacena y modifica la información. En programación, es una de las clases del patrón MVC Model View-Controller, que separa la complejidad del desarrollo en clases independientes.',
                'Parrafo6'=>'La lógica empresarial incluye procesos que realizan la entrada de datos, la consulta y la generación de informes. Es esta capa la que existe, todo el procesamiento se realiza en el backend y la aplicación es visible para el usuario.',
                'Parrafo7'=>'',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'2',
                'Imagen'=>'https://ayudaleyprotecciondatos.es/wp-content/uploads/2020/12/seguridad-logica.jpg',
                'slug'=>'logicas_acceso_negocio',
            ],
            [

                'Titulo'=>'Definir el concepto de nivel vinculado a programación web.',
                'Descripcion'=>'Este lenguaje de programación Web fue inventado por Tim Berners-Lee en 1986.',
                'Parrafo1'=>'Programación Web. Permite la creación de sitios dinámicos en Internet. 
                Esto se consigue generando los contenidos del sitio a través de una base de datos mediante lenguajes de programación Web.',
                'Parrafo2'=>'El más conocido de los lenguajes de programación Web es el HTML . 
                Se puede traducir como lenguaje de marcas hipertextuales, es el lenguaje usado para crear páginas Web en Internet.',
                'Parrafo3'=>'',
                'Parrafo4'=>'',
                'Parrafo5'=>'',
                'Parrafo6'=>'',
                'Parrafo7'=>'',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'2',
                'Imagen'=>'https://indexdesarrollo.com/wp-content/uploads/2017/11/aprender-programacion-web.jpg',
                'slug'=>'concepto_programacion_web',
                
            ],
            [
                'Titulo'=>'Explicar el proceso de planificación en dos niveles. ',
                'Descripcion'=>'Los sistemas comunes cliente/servidor son pertenecientes a la categoría de las aplicaciones de dos niveles. ',
                'Parrafo1'=>'En este tipo de aplicaciones el peso del cálculo recae en el cliente, mientras que el servidor hace la parte menos 
                pesada, y eso que los clientes suelen ser máquinas menos potentes que los servidores',
                'Parrafo2'=>'Hasta ahora hemos supuesto que todos los procesos están en memoria principal. 
                Esta situación tiene implicaciones importantes para la planificación , ya que el tiempo de conmutación de procesos cuando hay que traer los procesos del disco es varios órdenes de magnitud mayor que cuando la conmutación es a un proceso que ya esta en memoria.',
                'Parrafo3'=>'Primero se carga en memoria un subconjunto de los procesos ejecutables , luego , el planificador se limita a escoger procesos de este subconjunto durante cierto tiempo.',
                'Parrafo4'=>'',
                'Parrafo5'=>'',
                'Parrafo6'=>'',
                'Parrafo7'=>'',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'2',
                'Imagen'=>'https://img-17.ccm2.net/wVmG6UkxgLC05NB5PHyFf3kHZ28=/9aae3b19862c41ddb63c96e94e46fc3a/ccm-encyclopedia/cs-images-2-tier.gif',
                'slug'=>'planificacion_de_dos_niveles',
            ],
            [
                'Titulo'=>'Explicar el proceso de planificación en tres niveles.',
                'Descripcion'=>'Esta es una arquitectura de aplicaciones de software que esta bien establecida, ya que organiza las aplicaciones en tres niveles',
                'Parrafo1'=>'Este como su nombre lo indica, posee tres niveles informáticos lógicos y físicos: el nivel de presentación o interfaz de usuario; el nivel de aplicación, donde se procesan los datos; y el nivel de datos, donde se almacenan los datos asociados a la aplicación.',
                'Parrafo2'=>'Beneficios',
                'Parrafo3'=>'Con 3 niveles, cada parte podría ser realizada al mismo tiempo por diferentes grupos de programadores codificando en diferentes idiomas de los desarrolladores de otros niveles. Los módulos de esta arquitectura, se basa en cliente-servidor en la que el lógica de proceso funcional, acceso a datos, almacenamiento de datos informáticos e interfaz de usuario se desarrollan y mantienen como módulos independientes en plataformas separadas',
                'Parrafo4'=>'',
                'Parrafo5'=>'',
                'Parrafo6'=>'',
                'Parrafo7'=>'',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'2',
                'Imagen'=>'https://i0.wp.com/oness.sourceforge.net/proyecto/html/images/three_layers.gif',
                'slug'=>'planificacion_tres_niveles',
            ],
            [
                'Titulo'=>'Explicar el proceso de planificación multiniveles.',
                'Descripcion'=>'Se abarcara el proceso multinivel',
                'Parrafo1'=>'Podríamos ir separando nuestra aplicación en mas niveles lógicos, ejemplificando, vamos a querer que nuestra aplicación tenga diversas interfaces, o sea interface gráfica (standalone o desktop) y además interface Web.',
                'Parrafo2'=>'A medida que más servicios coloquemos a nuestra aplicación y a medida que más escalable lo imaginemos, mas capas lógicas van a irse agregando a nuestra arquitectura',
                'Parrafo3'=>'',
                'Parrafo4'=>'',
                'Parrafo5'=>'',
                'Parrafo6'=>'',
                'Parrafo7'=>'',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'2',
                'Imagen'=>'https://www.infor.uva.es/~jvegas/cursos/buendia/pordocente/img3.gif',
                'slug'=>'planifiacion_multinivel',
            ],
            [
                'Titulo'=>'Identificar problemas de actualización y mantenimiento de aplicaciones multinivel.',
                'Descripcion'=>'Se Identificaran, como resultan los problemas de la actualizacion, asi como es el funcionamiento del mantenimiento',
                'Parrafo1'=>'Actualizacion',
                'Parrafo2'=>'El usar diversos tecnologías, demandará un más grande nivel de entendimiento por parte del conjunto de desarrolladores. ',
                'Parrafo3'=>'Varios, podríamos tener un plan publicado en cualquier servidor compartido, y esto podría llegar a ser desventajoso, debido el nivel de personalización y requerimientos que podríamos llegar a conseguir en la aplicación.',
                'Parrafo4'=>'Mantenimiento',
                'Parrafo5'=>'Para un mantenimiento este pasa por el dominio de técnicas de programación y de ingreso a bases de datos, condición esta que no se puede presuponer en un curso de divulgación como éste.',
                'Parrafo6'=>'',
                'Parrafo7'=>'',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'2',
                'Imagen'=>'',
                'slug'=>'actulizacion_y_mantenimiento',    
            ],    
            [
                'Titulo'=>'Reconocer los conceptos de modelo, control y vista, en las arquitecturas Cliente/Servidor.',
                'Descripcion'=>'El Modelo es una representación de los datos que contiene el sistema, su lógica y sus mecanismos de persistencia.',
                'Parrafo1'=>'La Vista compone la información que se envía al cliente y los mecanismos con los cuales puede hacer una relación con el mismo.',
                'Parrafo2'=>'El Controlador este actúa  como intermediario entre el Modelo y la Vista, ya que este tendrá la tarea de  gestionar el flujo de 
                información entre los mismos y las transformaciones para adaptar los datos a las necesidades de cada uno.',
                'Parrafo3'=>'',
                'Parrafo4'=>'',
                'Parrafo5'=>'',
                'Parrafo6'=>'',
                'Parrafo7'=>'',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'2',
                'Imagen'=>'https://codigofacilito.com/photo_generales_store/29.jpg',
                'slug'=>'modelo_vista_controlador',
            ],
            [
                'Titulo'=>'Reconocer el concepto del Modelo Vista Controlador (MVC) en las arquitecturas  Cliente/Servidor.',
                'Descripcion'=>'Modelo Vista Controlador (MVC) es un estilo de arquitectura de software que separa los datos de una aplicación',
                'Parrafo1'=>'Se trata de un modelo muy maduro y que ha demostrado su validez a lo largo de los años en todo tipo de aplicaciones, y sobre multitud de lenguajes y plataformas de desarrollo',
                'Parrafo2'=>'Lleva un registro de las vistas y controladores del sistema.',
                'Parrafo3'=>'Si estamos ante un modelo activo, notificará a las vistas los cambios que en los datos pueda producir un agente externo 
                (por ejemplo, un fichero por lotes  que actualiza los datos, un temporizador que desencadena una inserción, etc.).',
                'Parrafo4'=>'',
                'Parrafo5'=>'',
                'Parrafo6'=>'',
                'Parrafo7'=>'',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'2',
                'Imagen'=>'https://seguridad.cicese.mx/uploads/notautic/utic23-5a3c250c42cae.png',
                'slug'=>'modelo_en_arquitectura_cliente_servidor',
            ],
            [
                'Titulo'=>'Explicar el proceso de flujo de control a partir del MVC, en las arquitecturas  Cliente/Servidor. ',
                'Descripcion'=>'Se explicara el flujo, de una manera sencilla',
                'Parrafo1'=>'El cliente hace una acción en la interfaz',
                'Parrafo2'=>'El controlador notifica al modelo la acción del cliente, lo cual puede involucrar un cambio del estado del modelo (si no es una mera consulta) ',
                'Parrafo3'=>'La vista toma los datos del modelo ',
                'Parrafo4'=>'La interfaz de usuario espera otra interacción del usuario, que comenzará otro nuevo ciclo',
                'Parrafo5'=>'',
                'Parrafo6'=>'',
                'Parrafo7'=>'',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'2',
                'Imagen'=>'https://www.arquitecturajava.com/wp-content/uploads/patronMVCCliente-2.png',
                'slug'=>'flujo_de_control_mvc',
            ],
            [
                'Titulo'=>'Describir el desarrollo de software a partir del MVC, en las arquitecturas Cliente/Servidor.',
                'Descripcion'=>'Cada uno de los procesos que se desarrolla tiene un proceso, es por ello que debemos entender lo siguoente:',
                'Parrafo1'=>'Al desarrollar software utilizando el MVC, posibilita dividir los elementos de nuestra aplicación dependiendo de 
                la responsabilidad que poseen, esto desea decir que una vez que hacemos un cambio en alguna parte de nuestro código, 
                esto no perjudique otra parte del mismo. Ejemplificando, si modificamos nuestra Base de Datos, solamente deberíamos 
                cambiar el modelo que es quién se ocupa de los datos y lo demás de la aplicación debe quedar intacta. ',
                'Parrafo2'=>'Una vez que el cliente manda una súplica al navegador, mencionemos quiere ver el curso de AngularJS, el 
                controlador responde a la solicitud, ya que él es el que controla la lógica de la app, 
                cuando el controlador nota que el cliente pidió el curso de Angular, le exige al modelo la información del curso.',
                'Parrafo3'=>'',
                'Parrafo4'=>'',
                'Parrafo5'=>'',
                'Parrafo6'=>'',
                'Parrafo7'=>'',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'2',
                'Imagen'=>'',
                'slug'=>'desarrollo_apartir_del_mvc',    
            ],    
            [
                'Titulo'=>'Definir el concepto de comunicación orientada a conexión e interfaz de programación de aplicaciones (API).',
                'Descripcion'=>'Identificar lo que es una comunicacion orientada a conexion, asi como la interfaz de programacion de aplicaciones',
                'Parrafo1'=>'Comunicación orientada a conexión',
                'Parrafo2'=>'La comunicación orientada a la conexión es uno de los tipos de comunicación de datos que requiere una sobrecarga al momento de 
                configurar una solicitud de conexión antes de enviar cualquier tipo de mensaje de comunicación de datos',
                'Parrafo3'=>'Interfaz de programación de aplicaciones',
                'Parrafo3'=>'Es un grupo de definiciones y protocolos que se utiliza para desarrollar e integrar el software de las aplicaciones, con el fin de permitir 
                la comunicación entre dos aplicaciones de software a través de un conjunto de reglas.',
                'Parrafo4'=>'',
                'Parrafo5'=>'',
                'Parrafo6'=>'',
                'Parrafo7'=>'',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'2',
                'Imagen'=>'https://www.imagar.com/wp-content/uploads/2019/10/queesunapi.png',
                'slug'=>'comunicacion_orientada_y_api',
            ],
            [
                'Titulo'=>'Explicar el proceso de comunicación y configuración orientada a conexión e interfaz de programación de aplicaciones (API).',
                'Descripcion'=>'Se explicara el proces de su funcionamiento y configuracion',
                'Parrafo1'=>'¿Como es?',
                'Parrafo2'=>'En general, los desarrolladores de una aplicación de software ponen a disposición la interfaz de programación de aplicaciones 
                para que los programadores de otras aplicaciones puedan utilizar la interfaz. 
                La Interfaz de Programación de Aplicaciones define cómo se recibe y devuelve la información y los datos entre los módulos. 
                Google, por ejemplo, ofrece una API para permitir a otros programadores integrar sus propias aplicaciones en los servicios de Google. 
                Para la comunicación entre aplicaciones, en particular en la web, el protocolo REST es muy popular.',
                'Parrafo3'=>'Para configurar la solicitud de procedimiento, debería configurar un procedimiento HTTP, la ruta a un recurso de API, 
                los encabezados y los fronteras de cadenas de consulta aplicables.
                Además configura una carga una vez que el procedimiento HTTP es POST, PUTo PATCH.',
                'Parrafo4'=>'Para una incorporación que no sea de proxy, debería configurar respuestas de procedimiento para especificar 
                los destinos necesarios u opcionales de las asignaciones. Dichos convierten los encabezados o 
                el cuerpo humano de contestación de la incorporación en encabezados o en cuerpo humano de contestación de procedimiento. ',
                'Parrafo5'=>'',
                'Parrafo6'=>'',
                'Parrafo7'=>'',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'2',
                'Imagen'=>'https://cambiodigital-ol.com/wp-content/uploads/2020/04/APIs.jpg',
                'slug'=>'api_configuracion', 
            ],
            [
                'Titulo'=>'Definir el concepto de sockets.',
                'Descripcion'=>'¿Que es un socket enfocado en cliente servidor?',
                'Parrafo1'=>'es un tunel de comunicación que ayuda a que 2 aplicaciones se comuniquen, 
                los sockets son la base de internet y de sus protocolos como HTTP, FTP, SMTP, etc.',
                'Parrafo2'=>'',
                'Parrafo3'=>'',
                'Parrafo4'=>'',
                'Parrafo5'=>'',
                'Parrafo6'=>'',
                'Parrafo7'=>'',
                'Parrafo8'=>'',
                'Parrafo9'=>'',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',
                'Unidad'=>'2',
                'Imagen'=>'https://image.slidesharecdn.com/semana8apidesocket-161105155254/95/semana-8-api-de-socket-12-638.jpg?cb=1478361215',
                'slug'=>'concepto_socket',
            ],    
            [ 
                'Titulo'=>'Explicar el proceso del uso de sockets en aplicaciones Cliente/Servidor.',
                'Descripcion'=>'¿Como es que estos funcionan entre si? ',
                'Parrafo1'=>'Para que se pueda realizar una comunicación entre sockets, es necesario tener en cuenta lo siguiente:',
                'Parrafo2'=>'El servidor siempre escucha por un puerto (es decir a través de donde viajaran los datos) lo que el cliente diga y si tiene respuesta, entonces responde.',
                'Parrafo3'=>'El cliente se conecta al servidor por el puerto y comienza a enviar peticiones y queda pendiente de que el servidor le de  respuestas.',
                'Parrafo4'=>'	Los datos que se envían, viajan a través de puertos. Y estos están compuestos de un puerto de entrada para el servidor y un puerto de salida para el cliente.',
                'Parrafo5'=>'	El protocolo, debe estar para que pueda existir comunicación entre las 2 aplicaciones, estas mismas deben estar programadas para responderse entre si, por lo cual lo denominamos como protocolo.',
                'Parrafo6'=>'¿Como se realiza una comunicacion?',
                'Parrafo7'=>'Para poder realizar una comunicacion, lo podemos realizar mediante dos formas',
                'Parrafo8'=>'De manera remota, y esto se hace  cuando las 2 aplicaciones están en diferentes computadoras, la aplicación cliente se conecta la dirección IP y puerto del servidor.',
                'Parrafo9'=>'De manera local, y esta se ejecuta  cuando las 2 aplicaciones están en la misma computadora, se ocupa una  dirección IP de LOOPBACK la cual es LOCALHOST  o 127.0.0.1.',
                'Parrafo10'=>'',
                'Parrafo11'=>'',
                'Parrafo12'=>'',
                'Parrafo13'=>'',
                'Parrafo14'=>'',
                'Parrafo15'=>'',
                'Parrafo16'=>'',
                'Parrafo17'=>'',
                'Parrafo18'=>'',
                'Parrafo19'=>'',
                'Parrafo20'=>'',
                'Parrafo21'=>'',     
                'Unidad'=>'2',
                'Imagen'=>'https://i.ytimg.com/vi/0-l8dAI6JRs/maxresdefault.jpg',
                'slug'=>'uso_de_sockets',
            ]
        ]);
    }
}
